### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'map'

### ISSUE THREAD

**Issue by lognaturel** [delcroip/xlsformpo#1]
Thanks for sharing this! I was hoping to give it a try but am getting `AttributeError: 'DataFrame' object has no attribute 'map'`:

```
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    process_xform(input_path, source_lang) # output is the default output directory
  File "/xlsformpo/xlsformpo/services.py", line 28, in process_xform
    dfs = parse_sheets(input_file)
  File "/xlsformpo/xlsformpo/serializers/xlsform.py", line 44, in parse_sheets
    df = df.dropna(how='all').map(lambda x: x.strip() if type(x)==str else x)
  File "/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'map'
```

`pandas` 2.0.3, python 3.8.1; running `python main.py -i 'foo.xlsx'` at the command line

**Comment by delcroip** [comment]
I don't know why I just saw that issue,I will have a look

**Comment by delcroip** [comment]
It should work now, this issue was not appearing with pandas 2.1.4 but with 2.0.3
br 

pythom 3.9 or 3.11, pandas 2.1.4

**Comment by lognaturel** [comment]
Thank you! Something made me think it was targeting Python 3.8 but now I’m not sure what. 

Thanks for looking into it and I’ll make sure to try again soon.

**Comment by delcroip** [comment]
Maybe because it says from 3.8 onward

`python_requires='>=3.8, <4',`

but the issue was clearly pandas 2.0.3 but it should work now with that version
